### ISSUE TITLE
virtual or search folders do offer contextmenu but don't alert

### ISSUE THREAD

**Issue by bits-fritz** [tjeb/Mailbox-Alert#13]
I have several search folders which I would like to alert incoming Mails.

The context menu appears, I can set configuration, but incoming mails don't
start alert.

Mailbox Alert 0.22.1
Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.9.0

**Comment by omgiafs** [comment]
Similar issue.
I have account on MS Exchange server, provided by Owl extension. Mailbox alert for "Incoming" folder works perfect.
Also i have a folder "Test" created on same level as "Incoming". Some emails forwared into "Test" folder by filtering rules. For "Test" folder Mailbox Alert enabled too.
Problem is: "Mailbox Alert" don't start alert after new email appearing in "Test" folder.

I used extension "Exquilla" earlier than "Owl", and Mailbox Alerts worked perfect with all folders i wanted. But it was on Thunderbird 60. 
Later TB was upgraded from 60 to 68 and extension serving MS Exchange account was changed from Exquilla to Owl. Therefore, I can’t say the reason why the alerts stopped working.

Mailbox Alert 0.22.1
Windows 10 x64, Thunderbird 68.2.2 (32 bit).

**UPDATE**. I tried Exquilla with TB 68, and MailBox alert works with custom virtual folders. TB68 and Owl - no Mailbox alerts.

There is a bug  in Mailbox Alert with accounts provided by Owl extension.

**Comment by tjeb** [comment]
It could be that virtual folders aren't handled like normal ones in the internal API's of Thunderbird (most notably internal signaling of new messages), in which case i'm not sure I can fix it.

The signaling changed wildly in every release since they dropped sane versioning, so perhaps it has solved itself by now. If this is still an issue with TB 78, there is still a chance that the next bigger release (not the very next one, which is bugfix only) may solve this issue, since TB will provide a new mechanism for callbacks on incoming mail.

Alternatively, perhaps setting Mailbox Alert as a message filter action might also help, but otherwise I'm afraid I can't do much about it.
