### ISSUE TITLE
Command does not allow unicode characters

### ISSUE THREAD

**Issue by hpaantee** [tjeb/Mailbox-Alert#22]
Hello,

when trying to use notify-send via a command, it does not accept unicode characters. For example if I try to use `notify-send "%server · %sendername"` it does not show any notification, but when I replace the middle dot by a dash.
The same command works (except for `%server` and `%sendername`) when executed in zsh or bash.

Cheers,
hpaantee

**Comment by tjeb** [comment]
Sorry, I have been ignoring issues on github for way too long.

I've been playing around with it and found the same issue. I have made a test script that writes the arguments to a file, and apparently it ends up being encoded with ISO-8859 instead of UTF-8. notify-send does not appear to be able to handle iso-8859; notify-send does nothing and returns an error code 256.

I have no idea where this happens, as everything seems to be UTF-8 in the script itself, but I do have a workaround for now; by converting the arguments to UTF-8 in a script which itself calls notify-send:

    #!/bin/sh
    /usr/bin/notify-send $(echo $@ | iconv -f iso-8859-1 -t utf-8)

Save this somewhere, make it executable, and use that, and it should work for now.

**Comment by tjeb** [comment]
I think I have found a workaround internally. With the patch I just committed it pretends that the encoding of the arguments is UTF-16. This isn't the case, but it does make TB convert it to UTF-8 internally, just before execution. Unless I can think of a better way to do this, this will be in the next release.
