### ISSUE TITLE
Feature request: Trigger custom alert based on time of day

### ISSUE THREAD

**Issue by explor202** [tjeb/Mailbox-Alert#33]
I'm not sure if it's within the scope of this add-on, but I'd love to see an option to trigger a custom alert based on the time of day an email is received. Right now I use custom voice alerts for each of my email accounts, but I'd like to further customize them by the time of day, using a time range. For instance, any email received between 12:00 AM and 11:59 AM would have a custom alert "Good morning John, new Hotmail email has arrived". Any email received between 12:00 PM and 4:59 PM would have a custom alert "Good afternoon", then from 5:00 PM to 11:59 PM would be "Good evening". Could that functionality be added to this add-on?

**Comment by StayPirate** [comment]
You could create a bash script which plays a different audio file according to the date output, then you can configure mailbox-alert to execute it once an email arrive.

You can either use the same script to generate toast notification via `notify-send`. This will solve the other problem you described #32 since notifications won't overlap on your screen anymore. Check [here](https://github.com/tjeb/Mailbox-Alert/issues/31#issuecomment-778136983) for an example.

**Comment by explor202** [comment]
@StayPirate Thanks for the suggestions. I've never worked with a bash script but will look into it.

**Comment by explor202** [comment]
I created some .bat files (yes, I know they're not bash lol) to play the specific notifications, but when I test the set up I get an access denied message in the cmd window. I've tried different permission settings, but none have worked. Can Mailbox-Alert run .bat files? If I can get that set up, I should then be able to edit the .bat files and add parameters to check the time and play the correct notification afterwards.

**Comment by explor202** [comment]
@StayPirate I've taken a completely different approach to this now. I created some scripts using AutoIt that will play the account notifications I've created based on the time of day. Plus, the script is limited to running a single occurrence, so no more duplicate notifications are being played. Thanks again for your suggestion.
