### ISSUE TITLE
Alerts trigger twice

### ISSUE THREAD

**Issue by haarp** [tjeb/Mailbox-Alert#37]
Hello,

I have Thunderbird alerts disabled and use this extension for alerting instead. I have two alerts set, one for a notification, one for sound. Both alerts are enabled for the topmost folder (account) and "Alert for child folders" is enabled.

When new mail arrives, I get *two* alerts of each kind in quick succession, i.e. two notifications and two sounds.

I can't tell why this happens. When "Alert for child folders" is disabled, I get no alert whatsoever.

Thunderbird 78, Mailbox Alert 0.27, Gentoo Linux

Any ideas? Thanks!

**Comment by jolange** [comment]
I observe the same issue, but in my case the "problem" obviously is that I've got **two thunderbird windows** open: One for mails and one for the calendar. But thunderbird does not allow to open a window with *only* the calendar tab open, but it always also has a mail tab.
So I am pretty sure that the alert is triggered in every window once.

I stumbled across your issue here, while looking for a solution to my problem. @haarp do you also have more than one window open, or are these really two separate issues?

**Comment by haarp** [comment]
I only ever have one window open, which is handled by Birdtray. But maybe there is a hidden window or dialog somewhere?

FWIW, I'm not currently encountering this issue anymore, but I'm not sure why.

**Comment by ApopheniaPays** [comment]
Wait, is this why I wake up every morning to dozens of repeated notifications? Some days it takes me 20 minutes to close all the hundreds of notifications I wake up to. 

I have a FiltaQuilla script that opens every mailbox in a new window when it receives an email, so I have a bunch of open windows I can click through quickly to see my new mail without having to hunt through a long folder list. So often I do have many windows open. 

Why in the world would this send notifications per window instead of per new email? Just because I have 15 windows open doesn't mean I want 15 notifications for each new email, that's seriously bad design and it's causing actual problems for me, I get enough mail and have enough windows open that this is taking up a lot of time every morning just clicking through the hundreds of notifications to close them. Not to mention that the app I'm using for notification, terminal-notifier (because mailbox-alert's own notifications are unusable, you can't see more than one at a time and they don't have a Close button), ground my computer to a halt today because I happened to have gotten new emails in a lot of folders and before I got to them each new email started spawning dozens of instances of terminal-notifier. I couldn't figure out why. Now I understand, because this extension for some reason assumes the number of windows I have open is the number of notifications I should get. 

Wow. This needs to be fixed.

**Comment by tjeb** [comment]
Fix will go into next release (0.29). Be aware that you probably need to restart thunderbird for the changes to take effect once the update is installed.
