### ISSUE TITLE
Feature request - add SMS alerts

### ISSUE THREAD

**Issue by explor202** [tjeb/Mailbox-Alert#40]
It's probably out of the scope of this add-on, but I would love to see an option to trigger an SMS alert when a new email arrives. To save data and reduce my plan cost, I no longer have email on my phone. However it would be nice to still know when a new email arrives via a text sent to my phone.

**Comment by kupietools** [comment]
Just a suggestion... You can do this with free services like If This, Then That or Zapier. This would be better than using Mailbox-Alert in any case, because they'll monitor your server, and notify you when the email is received there, even before it's downloaded to your computer. 

If you needed to, you could use Mailbox Alert's ability to run an external program to run a script on your system that uses a service to send an SMS. But having done things like this in the past, it's a complicated solution, if it was me I'd use IFTTT or zapier. 

The final option is to have a mail filter set up that forwards incoming mail to your phone company's SMS email gateway, if they have one... for instances, you can text AT&T customers by emailing [10 digit number]@txt.att.net. However, I've found this to be unreliable nowdays due to carrier anti-spam efforts, and have stopped using it myself.

**Comment by kupietools** [comment]
Hey, by sheer coincidence, I just a moment ago ran across this. Seems like it's clearly for developers, but if that's you, they specifically mention SMS notification of new emails as a use case: [https://github.com/mailscript/cli](https://github.com/mailscript/cli)

**Comment by explor202** [comment]
@kupietools Thanks for the pointers. I did look at Zapier once but don't recall why I decided against it; I'll check out the other suggestions though. Since there's been no response from the dev on my request, I'll close this one.
